services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
  frontend-app:
    container_name: frontend-app
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    volumes:
      - ./frontend-app:/frontend-app
      - /frontend-app/node_modules
      - /frontend-app/.next
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # This environment variable can help with hot reloading